sudo: required #making use of docker (linux)
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD) 
    #this will create a env varable named SHA that receives the uid of the most recent sha/commit in the tree
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    #disable gc prompts that require user input, because it will run inside a travis enviroment and we wont have access
before_install: 
  #decrypts the encrypted file and places in our root project directory
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null; #downloads google cloud sdk and install locally in the travis enviroment
  - source $HOME/google-cloud-sdk/path.bash.inc # look at default install directory of gc sdk, and apply some configs that will be sourced at the file path.bash.inc
  - gcloud components update kubectl # installs kubectl inside of travis enviroment
# it will be used for applying config files and run some imperatiave commands
  - gcloud auth activate-service-account --key-file service-account.json
#tells gcloud who we are and gives us access to our account, via a file.json that we will create, check tips
  - gcloud config set project multi-k8s-327220
#defines the ID of the project displayed in GC console (open the list of project to colect id)
  - gcloud config set compute/zone southamerica-east1-a
#computzone defined in the creation of the cluster
  - gcloud container clusters get-credentials multi-cluster
  #uses the the cluster name that we defined in the Gcloud
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  #login to docker
  - docker build -t mvsa22/react-test -f ./client/Dockerfile.dev ./client
  # file to build and build context

script:
  - docker run -e CI=true mvsa22/react-test npm test

deploy:
  provider: script
  #external file that we created
  script: bash ./deploy.sh
  #o script de deploy so vai ser rodado para o codigo que estiver na master
  on:
    branch: master